# This is a basic workflow to help you get started with Actions

name: Main

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Dependency audit
        run: yarn audit
        
      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier:check

      - name: Test
        run: yarn test
