# This is a basic workflow to help you get started with Actions

name: Main

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '.tmp'
          key: ${{ runner.os }}-isolatetmp
          restore-keys: |
            ${{ runner.os }}-isolatetmp

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install packages
        run: pnpm install

      - name: Dependency audit
        run: pnpm audit --groups dependencies

      - name: Lint
        run: pnpm lint

      - name: Prettier
        run: pnpm prettier:check

      - name: Test
        run: pnpm test

      - name: Test isolate
        run: |
          pnpm global add @betty-blocks/cli
          pnpm test:isolate
